@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.specialai.level;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;