@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.specialai.core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;