modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/FatherToast/SpecialAI/issues/"

[[mods]]
logoFile = "banner.png"
authors = "Father Toast"
credits = "Mother Toast & Baby Toast"
version = "${file.jarVersion}"
#displayTest = "IGNORE_SERVER_VERSION" #TODO un-comment for 1.19.2+
displayName = "Special AI"
modId = "specialai"
description = '''
Special AI modifies the behaviors of entities to create new challenges and make the world feel more alive.

This mod is highly configurable and each feature has at least one config option associated with it.
Browsing the configs will provide information on all the mod's features. If more in-depth information is needed, ask in the Discord server.


Download: https://www.curseforge.com/members/fathertoast/projects/

Source: https://github.com/FatherToast/

Discussion: https://discord.gg/GFTzTdX
'''

[[dependencies.specialai]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.specialai]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.specialai]]
modId = "crust"
mandatory = true
versionRange = "[1.3.4,)"
ordering = "NONE"
side = "BOTH"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="" #optional