@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.specialai.ai.griefing;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;