@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.specialai.ai.griefing;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;