@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.specialai;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;