@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package fathertoast.specialai.ai;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;