package fathertoast.specialai.ai;

import fathertoast.specialai.config.Config;
import net.minecraft.util.Mth;
import net.minecraft.util.StringRepresentable;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.ai.goal.Goal;
import net.minecraft.world.entity.ai.navigation.GroundPathNavigation;
import net.minecraft.world.entity.ai.navigation.WaterBoundPathNavigation;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.*;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.horse.AbstractHorse;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.npc.AbstractVillager;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.AxeItem;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.EnchantmentHelper;
import net.minecraft.world.level.pathfinder.Node;
import net.minecraft.world.level.pathfinder.Path;
import net.minecraft.world.phys.Vec3;

import javax.annotation.Nullable;
import java.util.EnumSet;
import java.util.List;
import java.util.function.Consumer;

/**
 * This AI is a copy-paste of {@link net.minecraft.world.entity.ai.goal.MeleeAttackGoal}, but it is modified to allow normally passive mobs
 * (i.e., mobs with no attack damage attribute) to use it without crashing the game.
 * <br><br>
 * In addition, it will attempt to substitute path navigators in an attempt to get the pathfinding working on entities
 * that are not set up to use normal pathfinding. <u><strong>(This is a work in progress.)</u></strong>
 */
@SuppressWarnings( "UnstableApiUsage" )
public class UniversalMeleeAttackGoal extends Goal {
    
    /** The owner of this goal. */
    protected final Mob mob;
    /** The movement speed modifier to use when moving the owner towards its target. */
    private final double speedModifier;
    /** If true, the owner will try following its target even without line of sight. */
    private final boolean followingTargetEvenIfNotSeen;
    
    /** This goal's {@link MovementStrategy}. */
    private final MovementStrategy movementStrategy;
    
    /** The delay in ticks between attacking. */
    private int ticksUntilNextAttack;
    /** The delay in ticks between each time {@link UniversalMeleeAttackGoal#canUse()} is "fully" checked. */
    private long lastCanUseCheck;
    private static final long CAN_USE_COOLDOWN = 20L;
    
    /**
     * The current path generated by the owner's navigation.
     * This field as well as the other pathing-related fields below are only used
     * when {@link UniversalMeleeAttackGoal#movementStrategy} is {@link MovementStrategy#PATHER}.
     */
    private Path path;
    /** X, Y and Z target coordinates for pathing goal owners. */
    private double pathedTargetX;
    private double pathedTargetY;
    private double pathedTargetZ;
    /**
     * The delay in ticks until next time a new path is calculated.
     * This is only relevant if the goal owner utilized pathing.
     */
    private int ticksUntilNextPathRecalculation;
    /** Whether multiple failed pathing attempts should slow down new pathing attempts. */
    private final boolean canPenalize;
    /** The pathing cooldown penalty to use when {@link UniversalMeleeAttackGoal#canPenalize} is true. */
    private int failedPathFindingPenalty = 0;
    
    
    /**
     * @param owner  The owner of this AI.
     * @param memory Whether the owner needs line of sight to follow its target.
     */
    public UniversalMeleeAttackGoal( Mob owner, boolean memory ) {
        this( owner, memory, false );
    }
    
    /**
     * @param owner    The owner of this AI.
     * @param memory   Whether the owner needs line of sight to follow its target.
     * @param penalize If true, failed pathfinding attempts will result in slower
     *                 and slower recalculations to reduce CPU overhead. This is
     *                 only has an effect if the goal owned is deemed a pather
     *                 when passed into {@link UniversalMeleeAttackGoal#strategyOf(Mob)}.
     */
    public UniversalMeleeAttackGoal( Mob owner, boolean memory, boolean penalize ) {
        mob = owner;
        followingTargetEvenIfNotSeen = memory;
        canPenalize = penalize;
        speedModifier = attackingMoveSpeed( owner );
        movementStrategy = strategyOf( owner );
        
        setFlags( EnumSet.of( Goal.Flag.MOVE, Goal.Flag.LOOK ) );
    }
    
    /**
     * @return Returns the pathfinding speed multiplier for the entity while attacking.
     * This is not used for swimming entities or goal owners that are not considered pathfinders.
     */
    public static double attackingMoveSpeed( Mob entity ) {
        if( entity instanceof AbstractVillager ) {
            return 0.7;
        }
        if( entity instanceof Rabbit ) {
            return 3.3;
        }
        if( entity instanceof Chicken || entity instanceof AbstractFish ) {
            return 1.6;
        }
        if( entity instanceof Frog ) {
            return 1.5;
        }
        if( entity instanceof Animal ) {
            return 1.3;
        }
        return 1.0;
    }
    
    /** @return Returns the fallback attack damage attribute for entities that do not have the attribute registered. */
    public static float defaultAttackDamage( Mob entity ) {
        // Note: Default attack damage is 2.0 and the units are half-hearts, held item damage is added on to this
        // Most animals have 3.0, wolves have 4.0, and large animals have 6.0
        if( entity instanceof Sheep || entity instanceof Rabbit || entity instanceof Salmon ) {
            return 2.0F;
        }
        if( entity instanceof Chicken || entity instanceof AbstractFish
                || entity instanceof Bat || entity instanceof Parrot ) {
            return 1.0F;
        }
        if( entity instanceof Cow || entity instanceof AbstractHorse ) {
            return 4.0F;
        }
        if( entity instanceof Sniffer ) {
            return 6.0F;
        }
        return 3.0F;
    }
    
    /** @return Returns the fallback attack knockback attribute for entities that do not have the attribute registered. */
    public static float defaultAttackKnockback( Mob entity ) {
        // Note: Default attack knockback is 0.0 and the max is 5.0, level of knockback enchant on held item is added on to this
        // Most mobs have 0.0, hoglins/zoglins have 1.0 (but also 'throw' on hit), and ravagers have 1.5
        if( entity instanceof Pig || entity instanceof Cow ) {
            return 1.5F;
        }
        return 0.0F;
    }
    
    /**
     * @return The (likely) appropriate {@link MovementStrategy} for the given mob
     * based on its inheritance and navigation instance.
     */
    public static MovementStrategy strategyOf( Mob entity ) {
        MovementStrategy strategy = Config.GENERAL.ANIMALS.movementStratList.getOrElse( entity, MovementStrategy.AUTO );
        
        // Check if a specific strategy is specified by the config
        if( strategy != MovementStrategy.AUTO ) {
            return strategy;
        }
        
        // Squids require special handling
        if( entity instanceof Squid ) {
            return MovementStrategy.SQUID;
        }
        // So do bats
        if( entity instanceof Bat ) {
            return MovementStrategy.BAT;
        }
        // Assume flying mobs with ground nav don't use pathing
        if( entity instanceof FlyingMob && entity.getNavigation() instanceof GroundPathNavigation ) {
            return MovementStrategy.GENERIC_FLYING;
        }
        // Assume water animals without waterbound nav don't use pathing
        if( entity instanceof WaterAnimal && !(entity.getNavigation() instanceof WaterBoundPathNavigation) ) {
            return MovementStrategy.GENERIC_WATER;
        }
        // Assume mobs that have ground nav but no goals with MOVE flag don't use pathing
        if( entity.getNavigation() instanceof GroundPathNavigation
                && entity.goalSelector.getRunningGoals().anyMatch( ( task ) -> !task.getFlags().contains( Flag.MOVE ) ) ) {
            return MovementStrategy.GENERIC_GROUND;
        }
        // If no matching exceptions were found, assume the entity can pathfind
        return MovementStrategy.PATHER;
    }
    
    /**
     * @return True if this goal can start executing.
     * This is the first check that is run BEFORE
     * the goal starts executing.
     */
    @Override
    public boolean canUse() {
        final long gameTime = mob.level().getGameTime();
        
        if( movementStrategy == MovementStrategy.PATHER && gameTime - lastCanUseCheck < CAN_USE_COOLDOWN ) {
            return false;
        }
        else {
            final LivingEntity target = mob.getTarget();
            lastCanUseCheck = gameTime;
            
            if( target == null )
                return false;
            
            else if( !target.isAlive() )
                return false;
            
            else if( movementStrategy == MovementStrategy.PATHER ) {
                if( canPenalize ) {
                    if( --ticksUntilNextPathRecalculation <= 0 ) {
                        path = mob.getNavigation().createPath( target, 0 );
                        ticksUntilNextPathRecalculation = 4 + mob.getRandom().nextInt( 7 );
                        return path != null;
                    }
                    return true;
                }
                path = mob.getNavigation().createPath( target, 0 );
                
                if( path != null ) {
                    return true;
                }
            }
            return mob.distanceTo( target ) <= mob.getAttributeValue( Attributes.FOLLOW_RANGE );
        }
    }
    
    /** @return True if this goal can continue running. */
    @Override
    public boolean canContinueToUse() {
        LivingEntity target = mob.getTarget();
        
        if( target == null ) return false;
        
        if( !target.isAlive() ) return false;
        
        if( movementStrategy == MovementStrategy.PATHER ) {
            if( !followingTargetEvenIfNotSeen )
                return !mob.getNavigation().isDone();
        }
        else {
            if( mob.distanceTo( target ) > mob.getAttributeValue( Attributes.FOLLOW_RANGE ) )
                return false;
        }
        if( !mob.isWithinRestriction( target.blockPosition() ) )
            return false;
        
        return !isInvulPlayer( target );
    }
    
    /** Called when this goal starts executing. */
    @Override
    public void start() {
        if( movementStrategy == MovementStrategy.PATHER )
            mob.getNavigation().moveTo( path, speedModifier );
        mob.setAggressive( true );
        ticksUntilNextPathRecalculation = 0;
        ticksUntilNextAttack = 0;
    }
    
    /** Called when this goal stops executing. */
    @Override
    public void stop() {
        final LivingEntity target = mob.getTarget();
        
        if( !EntitySelector.NO_CREATIVE_OR_SPECTATOR.test( target ) ) {
            mob.setTarget( null );
        }
        mob.setAggressive( false );
        // Stop nav regardless
        mob.getNavigation().stop();
    }
    
    /** @return True if this goal should be updated every tick. */
    @Override
    public boolean requiresUpdateEveryTick() {
        return true;
    }
    
    @Override
    public void tick() {
        final LivingEntity target = mob.getTarget();
        
        if( target != null ) {
            final double distanceSqr = mob.getPerceivedTargetDistanceSquareForMeleeAttack( target );
            
            // Move owner towards target
            movementStrategy.move( this, mob, target, distanceSqr );
            
            // Maybe perform attack
            ticksUntilNextAttack = Math.max( ticksUntilNextAttack - 1, 0 );
            checkAndPerformAttack( target, distanceSqr );
        }
    }
    
    /**
     * Called every AI tick while the goal is active to check if the target can be attacked, and performs the attack if able.
     *
     * @param target      The entity's current target. Should not be null, but I don't trust it enough.
     * @param distanceSqr Distance squared from the entity to its target.
     */
    protected void checkAndPerformAttack( @Nullable LivingEntity target, double distanceSqr ) {
        // Target is null or an invul player, abort attacking
        if( target == null || isInvulPlayer( target ) ) {
            mob.setTarget( null );
            mob.getNavigation().stop();
        }
        else if( distanceSqr <= getAttackReachSqr( target ) && isTimeToAttack() ) {
            resetAttackCooldown();
            mob.swing( InteractionHand.MAIN_HAND );
            doHurtTarget( mob, target );
        }
    }
    
    /** @return True if the target is a player in either creative or spec mode. */
    private boolean isInvulPlayer( LivingEntity target ) {
        return target instanceof Player player && (player.isCreative() || player.isSpectator());
    }
    
    /**
     * An external implementation of a melee attack.
     *
     * @param target The target to attack.
     * @see Mob#doHurtTarget(Entity)
     */
    public static void doHurtTarget( Mob mob, Entity target ) {
        // Try to perform the attack organically
        try {
            mob.doHurtTarget( target );
            return;
        }
        catch( Exception ex ) {
            // Most likely failed due to missing attack damage/knockback attributes
        }
        
        // Get actual attributes if possible
        float damage;
        try {
            damage = (float) mob.getAttributeValue( Attributes.ATTACK_DAMAGE );
        }
        catch( Exception ex ) {
            // Failed to get attack damage, pick our own
            damage = defaultAttackDamage( mob );
        }
        float knockback;
        try {
            knockback = (float) mob.getAttributeValue( Attributes.ATTACK_KNOCKBACK );
        }
        catch( Exception ex ) {
            // Failed to get attack knockback, pick our own
            knockback = defaultAttackKnockback( mob );
        }
        
        // Modify based on enchantments and active effects
        if( target instanceof LivingEntity ) {
            damage += EnchantmentHelper.getDamageBonus( mob.getMainHandItem(), ((LivingEntity) target).getMobType() );
            knockback += (float) EnchantmentHelper.getKnockbackBonus( mob );
        }
        final int fire = EnchantmentHelper.getFireAspect( mob );
        if( fire > 0 ) {
            target.setSecondsOnFire( fire * 4 );
        }
        
        // Actually perform the attack
        if( target.hurt( mob.level().damageSources().mobAttack( mob ), damage ) ) {
            // Apply knockback
            if( knockback > 0.0F && target instanceof LivingEntity ) {
                final float yRot = (float) Math.toRadians( mob.getYRot() );
                ((LivingEntity) target).knockback( knockback * 0.5F, Mth.sin( yRot ), -Mth.cos( yRot ) );
                mob.setDeltaMovement( mob.getDeltaMovement().multiply( 0.6, 1.0, 0.6 ) );
            }
            // Handle shield
            if( target instanceof Player player ) {
                maybeDisableShield( mob, player, mob.getMainHandItem(), player.isUsingItem() ? player.getUseItem() : ItemStack.EMPTY );
            }
            
            final float effectiveDifficulty = mob.level().getCurrentDifficultyAt( mob.blockPosition() ).getEffectiveDifficulty();
            if( mob.getMainHandItem().isEmpty() && mob.isOnFire() && mob.getRandom().nextFloat() < effectiveDifficulty * 0.3F ) {
                target.setSecondsOnFire( 2 * (int) effectiveDifficulty );
            }
            
            mob.doEnchantDamageEffects( mob, target );
            mob.setLastHurtMob( target );
        }
    }
    
    /**
     * An external implementation of the shield disable event.
     *
     * @param target The target to attack.
     * @see Mob#maybeDisableShield(Player, ItemStack, ItemStack)
     */
    @SuppressWarnings( "JavadocReference" )
    private static void maybeDisableShield( Mob mob, Player target, ItemStack weapon, ItemStack possibleShield ) {
        if( !weapon.isEmpty() && !possibleShield.isEmpty() && weapon.getItem() instanceof AxeItem && possibleShield.getItem() == Items.SHIELD ) {
            final float disableChance = 0.25F + (float) EnchantmentHelper.getBlockEfficiency( mob ) * 0.05F;
            if( mob.getRandom().nextFloat() < disableChance ) {
                target.getCooldowns().addCooldown( Items.SHIELD, 100 );
                mob.level().broadcastEntityEvent( target, (byte) 30 );
            }
        }
    }
    
    /** Resets attack cooldown. */
    protected void resetAttackCooldown() {
        ticksUntilNextAttack = adjustedTickDelay( 20 );
    }
    
    /** @return True if the tick now is the time to attack. */
    protected boolean isTimeToAttack() {
        return ticksUntilNextAttack <= 0;
    }
    
    protected double getAttackReachSqr( LivingEntity target ) {
        return mob.getBbWidth() * 2.0F * mob.getBbWidth() * 2.0F + target.getBbWidth();
    }
    
    /**
     * Used to determine what strategy to use when moving
     * the owner closer to its attack target.
     */
    public enum MovementStrategy implements StringRepresentable {
        // Does nothing. This is primarily used in the default config's default entry
        // to signal that Special AI should manually pick a suitable movement strategy.
        AUTO( "auto", List.of(
                "Tells Special AI to try and assume the likely best strategy for the mob."
        ),
                ( ctx ) -> { } ),
        // Any mob able to pathfind
        PATHER( "pather", List.of(
                "Used for mobs that supports pathfinding.",
                "Most vanilla monsters and animals supports pathfinding, such as zombies, creepers, pigs etc.",
                "Note that mobs that utilize the 'Brain AI' system will likely end up overriding traditional path navigation behavior."
        ),
                ( ctx ) -> {
                    final UniversalMeleeAttackGoal goal = ctx.goal;
                    final Mob mob = ctx.owner;
                    final LivingEntity target = ctx.target;
                    
                    // Look at target
                    mob.getLookControl().setLookAt( target, 30.0F, 30.0F );
                    
                    goal.ticksUntilNextPathRecalculation = Math.max( goal.ticksUntilNextPathRecalculation - 1, 0 );
                    
                    if( (goal.followingTargetEvenIfNotSeen || mob.getSensing().hasLineOfSight( target ))
                            && goal.ticksUntilNextPathRecalculation <= 0
                            && (goal.pathedTargetX == 0.0D && goal.pathedTargetY == 0.0D && goal.pathedTargetZ == 0.0D
                            || target.distanceToSqr( goal.pathedTargetX, goal.pathedTargetY, goal.pathedTargetZ ) >= 1.0D
                            || mob.getRandom().nextFloat() < 0.05F) ) {
                        goal.pathedTargetX = target.getX();
                        goal.pathedTargetY = target.getY();
                        goal.pathedTargetZ = target.getZ();
                        goal.ticksUntilNextPathRecalculation = 4 + mob.getRandom().nextInt( 7 );
                        
                        // Calculate pathing penalty, if enabled
                        if( goal.canPenalize ) {
                            goal.ticksUntilNextPathRecalculation += goal.failedPathFindingPenalty;
                            
                            if( mob.getNavigation().getPath() != null ) {
                                final Node node = mob.getNavigation().getPath().getEndNode();
                                
                                if( node != null && target.distanceToSqr( node.x, node.y, node.z ) < 1 )
                                    goal.failedPathFindingPenalty = 0;
                                else
                                    goal.failedPathFindingPenalty += 10;
                            }
                            else {
                                goal.failedPathFindingPenalty += 10;
                            }
                        }
                        if( ctx.attackDist > 1024.0D ) {
                            goal.ticksUntilNextPathRecalculation += 10;
                        }
                        else if( ctx.attackDist > 256.0D ) {
                            goal.ticksUntilNextPathRecalculation += 5;
                        }
                        if( !mob.getNavigation().moveTo( target, goal.speedModifier ) ) {
                            goal.ticksUntilNextPathRecalculation += 15;
                        }
                        goal.ticksUntilNextPathRecalculation = goal.adjustedTickDelay( goal.ticksUntilNextPathRecalculation );
                    }
                } ),
        // Water animal that does not use pathing
        GENERIC_WATER( "generic_water", List.of(
                "Useful for water mobs that do not support pathfinding.",
                "This strategy naively tries to move the mob directly towards its target when the mob is underwater," +
                        " using the mob's internal move control.",
                "Any restrictions in movement is effectively decided by the move control, which Special AI does not interact with.",
                "If the mob is on land and collides with something horizontally it will spam-jump to try and get past the obstacle."
        ),
                ( ctx ) -> {
                    final UniversalMeleeAttackGoal goal = ctx.goal;
                    final Mob mob = ctx.owner;
                    final LivingEntity target = ctx.target;
                    
                    if( (goal.followingTargetEvenIfNotSeen || mob.getSensing().hasLineOfSight( target )) ) {
                        // Look at target
                        mob.lookAt( target, 30.0F, 30.0F );
                        mob.getLookControl().setLookAt( target, 30.0F, 30.0F );
                        
                        if( target.distanceToSqr( mob ) >= 1.0D ) {
                            mob.getMoveControl().setWantedPosition( target.getX(), target.getY(), target.getZ(), 1.0 );
                            
                            // Jump if colliding with a wall outside water
                            if( !mob.isInWater() && mob.horizontalCollision ) {
                                mob.getJumpControl().jump();
                                mob.setJumping( true );
                            }
                        }
                    }
                } ),
        // Flying mob that does not use pathing
        GENERIC_FLYING( "generic_flying", List.of(
                "Useful for flying mobs that do not support pathfinding.",
                "This strategy naively tries to move the mob directly towards its target, using the mob's internal move control.",
                "Any restrictions in movement is effectively decided by the move control, which Special AI does not interact with."
        ),
                ( ctx ) -> {
                    final UniversalMeleeAttackGoal goal = ctx.goal;
                    final Mob mob = ctx.owner;
                    final LivingEntity target = ctx.target;
                    
                    if( (goal.followingTargetEvenIfNotSeen || mob.getSensing().hasLineOfSight( target )) ) {
                        // Look at target
                        mob.lookAt( target, 30.0F, 30.0F );
                        mob.getLookControl().setLookAt( target, 30.0F, 30.0F );
                        
                        if( ctx.attackDist >= 1.0D ) {
                            mob.getMoveControl().setWantedPosition( target.getX(), target.getY(), target.getZ(), 1.0 );
                        }
                    }
                } ),
        // Ground mobs that does not use pathing. This is probably highly unusual.
        GENERIC_GROUND( "generic_ground", List.of(
                "Useful for ground mobs that do not support pathfinding (probably very rare).",
                "This strategy naively tries to move the mob directly towards its target.",
                "The mob will spam-jump if it collides with something horizontally to try and get over whatever is in the way."
        ),
                ( ctx ) -> {
                    final UniversalMeleeAttackGoal goal = ctx.goal;
                    final Mob mob = ctx.owner;
                    final LivingEntity target = ctx.target;
                    
                    if( (goal.followingTargetEvenIfNotSeen || mob.getSensing().hasLineOfSight( target )) ) {
                        // Look at target
                        mob.lookAt( target, 30.0F, 30.0F );
                        mob.getLookControl().setLookAt( target, 30.0F, 30.0F );
                        
                        if( ctx.attackDist >= 1.0D ) {
                            Vec3 moveVec = getTargetVec( mob, target )
                                    .multiply( 1.0, 0.0, 1.0 )
                                    .scale( 0.1 );
                            
                            if( !mob.onGround() )
                                moveVec = moveVec.scale( 0.1 );
                            
                            mob.setDeltaMovement( mob.getDeltaMovement().add( moveVec ) );
                            
                            // Jump if colliding with a wall
                            if( mob.horizontalCollision ) {
                                mob.getJumpControl().jump();
                                mob.setJumping( true );
                            }
                        }
                    }
                } ),
        // Squids need special treatment *large thumbs up emoji*
        SQUID( "squid", List.of(
                "A special strategy designed specifically for unmodified, vanilla squids.",
                "Trying to use this strategy with a mob that does not inherit the squid entity class will crash the game."
        ),
                ( ctx ) -> {
                    final UniversalMeleeAttackGoal goal = ctx.goal;
                    final Squid squid = (Squid) ctx.owner;
                    final LivingEntity target = ctx.target;
                    
                    if( (goal.followingTargetEvenIfNotSeen || squid.hasLineOfSight( target )) ) {
                        // Look at target
                        squid.getLookControl().setLookAt( target, 30.0F, 30.0F );
                        
                        if( ctx.attackDist >= 1.0D ) {
                            final Vec3 moveVec = getTargetVec( squid, target ).scale( 0.4 );
                            squid.setMovementVector( (float) moveVec.x, (float) moveVec.y, (float) moveVec.z );
                        }
                    }
                } ),
        // Bats arguably do not need special treatment, but just in case
        BAT( "bat", List.of(
                "A special strategy designed specifically for unmodified, vanilla bats.",
                "Trying to use this strategy with a mob that does not inherit the bat entity class will crash the game."
        ),
                ( ctx ) -> {
                    final UniversalMeleeAttackGoal goal = ctx.goal;
                    final Bat bat = (Bat) ctx.owner;
                    final LivingEntity target = ctx.target;
                    
                    if( (goal.followingTargetEvenIfNotSeen || bat.getSensing().hasLineOfSight( target )) ) {
                        // Look at target
                        bat.getLookControl().setLookAt( target, 30.0F, 30.0F );
                        
                        if( ctx.attackDist >= 1.0D ) {
                            // Bats will probably never be resting while this goal is running but who knows
                            bat.setResting( false );
                            
                            // We don't really prevent the other movement the bat has,
                            // but it kinda works to make the movement sporadic, which is kinda nice
                            final Vec3 moveVec = getTargetVec( bat, target ).scale( 0.5 );
                            bat.setDeltaMovement( moveVec );
                        }
                    }
                } );
        
        final String name;
        final List<String> description;
        final Consumer<MoverContext> moveAction;
        
        MovementStrategy( String name, List<String> description, Consumer<MoverContext> moveAction ) {
            this.name = name;
            this.description = description;
            this.moveAction = moveAction;
        }
        
        /** Calls this movement strategy's move action with the given parameters. */
        public void move( UniversalMeleeAttackGoal goal, Mob owner, LivingEntity target, double attackDist ) {
            moveAction.accept( new MoverContext( goal, owner, target, attackDist ) );
        }
        
        /** @return This movement strategy's description. Used by config. */
        public List<String> getDescription() {
            return description;
        }
        
        /**
         * @return A normalized vector that goes between two entities where
         * the starting point is the current position of the first entity
         * and the ending point is the current center-Y position of the second entity.
         */
        private static Vec3 getTargetVec( Entity first, Entity second ) {
            return new Vec3(
                    second.getX() - first.getX(),
                    (second.getY() + (second.getBbHeight() / 2)) - first.getY(),
                    second.getZ() - first.getZ()
            ).normalize();
        }
        
        @Override
        public String getSerializedName() {
            return name;
        }
    }
    
    /** Context holder for {@link MovementStrategy} movement strategy handling. */
    record MoverContext(UniversalMeleeAttackGoal goal, Mob owner, LivingEntity target, double attackDist) { }
}
